-- ============================================================================
-- StoreFlow: multi-tenancy + sales analytics schema
-- Run this in the Supabase SQL Editor once. Safe to re-run (idempotent).
-- NOTE: This project currently uses the anon/publishable key directly (RLS
-- left as-is to match the existing setup). For production, enable RLS and
-- scope policies to auth.uid().
-- ============================================================================

-- 1) Stores table
CREATE TABLE IF NOT EXISTS stores (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO stores (id, name)
VALUES (1, 'Main Store')
ON CONFLICT (id) DO NOTHING;

-- 2) Scope existing products to a store
ALTER TABLE products
  ADD COLUMN IF NOT EXISTS store_id bigint NOT NULL DEFAULT 1 REFERENCES stores(id);

CREATE INDEX IF NOT EXISTS idx_products_store_id ON products (store_id);

-- 3) Sales table (one row per line item sold)
CREATE TABLE IF NOT EXISTS sales (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id bigint NOT NULL REFERENCES stores(id),
  product_id bigint REFERENCES products(id) ON DELETE SET NULL,
  sold_at timestamptz NOT NULL DEFAULT now(),
  quantity integer NOT NULL DEFAULT 1 CHECK (quantity > 0),
  unit_price numeric(10, 2) NOT NULL DEFAULT 0,
  unit_cost numeric(10, 2) NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_sales_store_id_sold_at ON sales (store_id, sold_at);

-- 4) Seed ~6 months of sales for store 1 (one sale per product per day,
--    quantity and price jittered for realistic trends)
INSERT INTO sales (store_id, product_id, sold_at, quantity, unit_price, unit_cost)
SELECT
  1,
  p.id,
  day.date,
  (1 + floor(random() * 6))::int AS quantity,
  round((p.price * (0.92 + random() * 0.16))::numeric, 2) AS unit_price,
  round((p.price * 0.55)::numeric, 2) AS unit_cost
FROM products p
CROSS JOIN LATERAL (
  SELECT now() - (n * interval '1 day') AS date
  FROM generate_series(1, 180) AS n
) AS day
WHERE p.store_id = 1;