-- ============================================================================
-- StoreFlow 002: Enterprise Retail OS (multi-warehouse, audit log, AI alerts,
--                offline idempotency)
-- Run in the Supabase SQL Editor AFTER 001_multi_tenant_sales.sql.
-- Safe to re-run (idempotent).
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1) Warehouses (multi-location inventory)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS warehouses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id bigint NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
  name text NOT NULL,
  location text,
  is_main boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_warehouses_store_id ON warehouses (store_id);
-- Only one main warehouse per store
CREATE UNIQUE INDEX IF NOT EXISTS uq_warehouses_store_main
  ON warehouses (store_id) WHERE is_main;

-- ---------------------------------------------------------------------------
-- 2) Inventory (per-warehouse stock; source of truth)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS inventory (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  warehouse_id bigint NOT NULL REFERENCES warehouses(id) ON DELETE CASCADE,
  product_id bigint NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  quantity integer NOT NULL DEFAULT 0,
  reorder_point integer NOT NULL DEFAULT 5,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (warehouse_id, product_id)
);

CREATE INDEX IF NOT EXISTS idx_inventory_warehouse_id ON inventory (warehouse_id);
CREATE INDEX IF NOT EXISTS idx_inventory_product_id ON inventory (product_id);

-- ---------------------------------------------------------------------------
-- 3) Stock transfers between warehouses
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS stock_transfers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id bigint NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
  product_id bigint NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  from_warehouse_id bigint REFERENCES warehouses(id) ON DELETE RESTRICT,
  to_warehouse_id bigint NOT NULL REFERENCES warehouses(id) ON DELETE CASCADE,
  quantity integer NOT NULL CHECK (quantity > 0),
  status text NOT NULL DEFAULT 'completed'
    CHECK (status IN ('pending', 'completed', 'cancelled')),
  note text,
  created_by_user_id uuid,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_stock_transfers_store_created
  ON stock_transfers (store_id, created_at DESC);

-- ---------------------------------------------------------------------------
-- 4) Immutable audit log (every stock change, price edit, sale, transfer)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS audit_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id bigint NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
  user_id uuid,
  action text NOT NULL,
  entity_type text NOT NULL,
  entity_id bigint,
  old_value jsonb,
  new_value jsonb,
  metadata jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_audit_logs_store_created
  ON audit_logs (store_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_logs_entity
  ON audit_logs (entity_type, entity_id);

-- Immutability: physical writes to audit_logs are rejected at the DB level.
CREATE OR REPLACE FUNCTION prevent_audit_mutation()
RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION 'audit_logs is immutable: updates and deletes are not allowed';
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_audit_no_update ON audit_logs;
CREATE TRIGGER trg_audit_no_update
BEFORE UPDATE ON audit_logs
FOR EACH ROW EXECUTE FUNCTION prevent_audit_mutation();

DROP TRIGGER IF EXISTS trg_audit_no_delete ON audit_logs;
CREATE TRIGGER trg_audit_no_delete
BEFORE DELETE ON audit_logs
FOR EACH ROW EXECUTE FUNCTION prevent_audit_mutation();

-- ---------------------------------------------------------------------------
-- 5) AI recommendations (written nightly by /api/cron/nightly-insights)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ai_recommendations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id bigint NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
  category text NOT NULL
    CHECK (category IN ('restock', 'pricing', 'insight', 'operational')),
  title text NOT NULL,
  message text NOT NULL,
  priority text NOT NULL DEFAULT 'normal'
    CHECK (priority IN ('high', 'medium', 'low')),
  data jsonb,
  is_read boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ai_recommendations_store_created
  ON ai_recommendations (store_id, created_at DESC);

-- ---------------------------------------------------------------------------
-- 6) Idempotency for offline POS sync (one sale record per client operation)
-- ---------------------------------------------------------------------------
ALTER TABLE sales ADD COLUMN IF NOT EXISTS client_op_id text;
CREATE UNIQUE INDEX IF NOT EXISTS uq_sales_store_client_op
  ON sales (store_id, client_op_id) WHERE client_op_id IS NOT NULL;

-- Convenience: where a product "lives". Keeps products.stock in sync with the
-- main warehouse's inventory quantity.
ALTER TABLE products ADD COLUMN IF NOT EXISTS warehouse_id bigint REFERENCES warehouses(id);

-- ---------------------------------------------------------------------------
-- 7) Seed warehouses for store 1 + backfill main-warehouse inventory
-- ---------------------------------------------------------------------------
INSERT INTO warehouses (store_id, name, location, is_main)
SELECT 1, 'Main Store', 'Storefront', true
WHERE NOT EXISTS (SELECT 1 FROM warehouses WHERE store_id = 1);

INSERT INTO warehouses (store_id, name, location, is_main)
SELECT 1, 'Secondary Warehouse', 'Back office', false
WHERE NOT EXISTS (
  SELECT 1 FROM warehouses WHERE store_id = 1 AND name = 'Secondary Warehouse'
);

INSERT INTO inventory (warehouse_id, product_id, quantity, reorder_point)
SELECT w.id, p.id, p.stock, 5
FROM products p
JOIN warehouses w ON w.store_id = p.store_id AND w.is_main
WHERE NOT EXISTS (
  SELECT 1
  FROM inventory i
  WHERE i.warehouse_id = w.id AND i.product_id = p.id
);